# 站点名称
site_name: 'Tools&Platform Guide'
# 仓库链接
repo_url: https://github.com/zjZSTU/tools-platform-guide.git
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2019, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.2.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
# 导航
nav:
    - Home: index.md
    - 开发工具:
        - VSCode: 
            - Home: './vscode/index.md'
            - 系统:
                - '引言': './vscode/system/引言.md'
                - '安装': './vscode/system/安装.md'
                - '布局': './vscode/system/布局.md'
                - '用户和工作空间设置': './vscode/system/用户和工作空间设置.md'
                - '快捷键设置': './vscode/system/快捷键设置.md'
                - '命令行操作': './vscode/system/命令行操作.md'
                - '代码片段': './vscode/system/代码片段.md'
                - 'tab键失效': './vscode/system/tab键失效.md'
            - 语言:
                - 'C++环境配置': './vscode/languages/C++环境配置.md'
                - 'Python环境配置': './vscode/languages/Python环境配置.md'
                - '[OpenCV 3.4.2]pylint检测错误': './vscode/languages/[OpenCV 3.4.2]pylint检测错误.md'
            - 插件:
                - 'Git设置': './vscode/third/git设置.md'
        - Jupyter:
                    - '[conda]JupyterLab安装': './jupyter/[conda]JupyterLab安装.md'
                    - '远程访问配置': './jupyter/远程访问配置.md'
                    - '基本功能介绍': './jupyter/基本功能介绍.md'
                    - '[PEP8]代码格式化': './jupyter/[PEP8]代码格式化.md'
                    - '目录生成插件': './jupyter/目录生成插件.md'
        - CLion:
            - '安装': './clion/安装.md'
            - 'OpenCV配置': './clion/OpenCV配置.md'
            - 'could not load cache': './clion/Error: could not load cache.md'
        - 'Android Studio':
            '安装': './android/android-studio/[Ubuntu]Android Studio安装.md'
            '[Ubuntu]启动器制作': './android/android-studio/[Ubuntu]启动器制作.md'
    - 开发平台:
        - NodeJS:
            - 'nodeJS安装': './node/nodeJS安装.md'
            - 'nodeJS初始化': './node/nodeJS初始化.md'
            - 'npm和cnpm': './node/npm和cnpm.md'
            - '[npm]查询': './node/[npm]查询.md'
            - '[npm]安装': './node/[npm]安装.md'
            - '[npm]卸载': './node/[npm]卸载.md'
            - '[package.json]脚本运行': './node/[package.json]脚本运行.md'
        - Anaconda:
            - '环境查询，安装，卸载，克隆': './anaconda/环境查询，安装，卸载，克隆.md'
            - '卸载包': './anaconda/卸载包.md'
            - '查询、安装指定版本': './anaconda/查询、安装指定版本.md'
            - '配置国内镜像源': './anaconda/配置国内镜像源.md'
        - Gradle:
            - '[Ubuntu]gradle同步失败': './android/gradle/[Ubuntu]gradle同步失败.md'
        - NDK:
            - 'NDK开发概述': './android/ndk/NDK开发概述.md'
            - 'ndk-build编译失败': './android/ndk/ndk-build编译失败.md'
            - '[Ubuntu]android studio配置javah和ndk-build': './android/ndk/[Ubuntu]android studio配置javah和ndk-build.md'
            - '[Ubuntu]NDK配置OpenCV': './android/ndk/[Ubuntu]NDK配置OpenCV.md'
            - 'libopencv_java3.so not found': './android/ndk/libopencv_java3.so not found.md'