# 站点名称
site_name: 'Tools&Platform Guide'
# 仓库链接
repo_url: https://github.com/zjZSTU/tools-platform-guide.git
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2019, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.2.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
# 导航
nav:
    - Home: index.md
    - VSCode: 
        - Home: './vscode/index.md'
        - 系统:
            - '引言': './vscode/system/引言.md'
            - '安装': './vscode/system/安装.md'
            - '布局': './vscode/system/布局.md'
            - '用户和工作空间设置': './vscode/system/用户和工作空间设置.md'
            - '快捷键设置': './vscode/system/快捷键设置.md'
            - '命令行操作': './vscode/system/命令行操作.md'
            - '代码片段': './vscode/system/代码片段.md'
            - 'tab键失效': './vscode/system/tab键失效.md'
        - 语言:
            - 'C++环境配置': './vscode/languages/C++环境配置.md'
            - 'Python环境配置': './vscode/languages/Python环境配置.md'
            - '[OpenCV 3.4.2]pylint检测错误': './vscode/languages/[OpenCV 3.4.2]pylint检测错误.md'
        - 插件:
            - 'Git设置': './vscode/third/git设置.md'